# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NoteMode.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from nmimports import *
from nmaccquestions import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Create the main horizontal layout
        self.mainSplitter = QtWidgets.QSplitter(QtCore.Qt.Horizontal, self.centralwidget)

        # Create the vertical splitters without setting geometry
        self.column1Splitter = QtWidgets.QSplitter(QtCore.Qt.Vertical)
        self.column2Splitter = QtWidgets.QSplitter(QtCore.Qt.Vertical)
        self.column3Splitter = QtWidgets.QSplitter(QtCore.Qt.Vertical)

        # Add the columns to the main splitter
        self.setupFirstColumn()
        self.setupSecondColumn()
        self.setupThirdColumn()

        # Set up the menu bar before calling retranslateUi
        self.setupMenuBar(MainWindow)

        # Add the columns to the main splitter
        self.mainSplitter.addWidget(self.column1Splitter)
        self.mainSplitter.addWidget(self.column2Splitter)
        self.mainSplitter.addWidget(self.column3Splitter)

        # Set the initial sizes of the columns based on the proportions
        totalWidth = MainWindow.size().width()
        self.mainSplitter.setSizes([totalWidth*3//8, totalWidth*4//8, totalWidth*1//8])

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Set the central widget and its layout with margins
        self.centralLayout = QtWidgets.QHBoxLayout(self.centralwidget)  # Create a layout for the centralwidget
        self.centralLayout.setContentsMargins(20, 20, 20, 20)
        self.centralLayout.addWidget(self.mainSplitter)  # Add the mainSplitter to the centralLayout
        self.centralwidget.setLayout(self.centralLayout)  # Set the layout to the centralwidget

        # V: Set central widget in main window
        MainWindow.setCentralWidget(self.mainSplitter)

    def setupMenuBar(self, MainWindow):
        # Set up the menu bar here
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 835, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuNote = QtWidgets.QMenu(self.menubar)
        self.menuNote.setObjectName("menuNote")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionNew_Cloze = QtWidgets.QAction(MainWindow)
        self.actionNew_Cloze.setObjectName("actionNew_Cloze")
        self.actionSame_Cloze = QtWidgets.QAction(MainWindow)
        self.actionSame_Cloze.setObjectName("actionSame_Cloze")
        self.actionBold = QtWidgets.QAction(MainWindow)
        self.actionBold.setObjectName("actionBold")
        self.actionUnderline = QtWidgets.QAction(MainWindow)
        self.actionUnderline.setObjectName("actionUnderline")
        self.actionItalicize = QtWidgets.QAction(MainWindow)
        self.actionItalicize.setObjectName("actionItalicize")
        self.actionAdd_Note = QtWidgets.QAction(MainWindow)
        self.actionAdd_Note.setObjectName("actionAdd_Note")
        self.actionAdd_Card = QtWidgets.QAction(MainWindow)
        self.actionAdd_Card.setObjectName("actionAdd_Card")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionExport)
        self.menuEdit.addAction(self.actionNew_Cloze)
        self.menuEdit.addAction(self.actionSame_Cloze)
        self.menuEdit.addAction(self.actionBold)
        self.menuEdit.addAction(self.actionUnderline)
        self.menuEdit.addAction(self.actionItalicize)
        self.menuNote.addAction(self.actionAdd_Note)
        self.menuNote.addAction(self.actionAdd_Card)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuNote.menuAction())

    def setupFirstColumn(self):
        # Set up the first column with a table
        self.tableGroupBox = QtWidgets.QGroupBox("Questions")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tableGroupBox)
        self.questionsTableWidget = QtWidgets.QTableWidget(1, 2)
        self.questionsTableWidget.horizontalHeader().setDefaultSectionSize(75)
        self.questionsTableWidget.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_4.addWidget(self.questionsTableWidget, 0, 0, 1, 1)
        self.column1Splitter.addWidget(self.tableGroupBox)

        # V: Button is being resized here
        self.buttonLayoutContainer = QtWidgets.QWidget()
        self.addButtonLayout = QtWidgets.QHBoxLayout(self.buttonLayoutContainer)
        self.addButtonLayout.addStretch()  # Left spacer
        self.addQPushButton = QtWidgets.QPushButton("Add Question")
        self.addQPushButton.setFixedSize(150, 50)  # Set a fixed size for the "+" button
        self.addButtonLayout.addWidget(self.addQPushButton)
        self.addButtonLayout.addStretch()  # Right spacer
        self.column1Splitter.addWidget(self.buttonLayoutContainer)
        
        # Create a new widget with a vertical layout for the line edits
        self.widget = QtWidgets.QWidget()
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setSpacing(2)  # V: Spacing adjusted for the Line Edits

        self.sortLineEdit = QtWidgets.QLineEdit()
        self.sortLineEdit.setPlaceholderText("Sort Identifier")
        self.verticalLayout.addWidget(self.sortLineEdit)
        self.numIDLineEdit = QtWidgets.QLineEdit()
        self.numIDLineEdit.setPlaceholderText("Numerical Identifier")
        self.verticalLayout.addWidget(self.numIDLineEdit)
        # Add the widget to the splitter
        self.column1Splitter.addWidget(self.widget)

    def setupSecondColumn(self):
        # Set up the second column with title and notes text edits
        self.titleGroupBox = QtWidgets.QGroupBox("Title")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.titleGroupBox)
        self.titleTextEdit = QtWidgets.QTextEdit()
        self.titleTextEdit.setMaximumHeight(50)  # Set a maximum height for the title text edit
        self.gridLayout_3.addWidget(self.titleTextEdit, 0, 0, 1, 1)
        self.notesGroupBox = QtWidgets.QGroupBox("Notes")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.notesGroupBox)
        self.notesTextEdit = QtWidgets.QTextEdit()
        self.gridLayout_2.addWidget(self.notesTextEdit, 0, 0, 1, 1)
        self.column2Splitter.addWidget(self.titleGroupBox)
        self.column2Splitter.addWidget(self.notesGroupBox)

        # Set the stretch factors for the splitter to allocate more space to the notes text edit
        self.column2Splitter.setStretchFactor(0, 1)  # Smaller stretch factor for title
        self.column2Splitter.setStretchFactor(1, 5)  # Larger stretch factor for notes

    def setupThirdColumn(self):
        # Set up the third column with all notes list view, add notes button, and topic text edit
        self.allNotesGroupBox = QtWidgets.QGroupBox("All Notes")
        self.gridLayout = QtWidgets.QGridLayout(self.allNotesGroupBox)
        self.allNotesScrollArea = QtWidgets.QScrollArea()
        self.allNotesScrollArea.setWidgetResizable(True)
        self.allNotesScrollAreaWidgetContents = QtWidgets.QWidget()
        self.allNotesScrollArea.setWidget(self.allNotesScrollAreaWidgetContents)
        
        self.allNoteListView = QtWidgets.QListView(self.allNotesScrollAreaWidgetContents)
        layout = QtWidgets.QVBoxLayout(self.allNotesScrollAreaWidgetContents)
        layout.addWidget(self.allNoteListView)
        
        self.gridLayout.addWidget(self.allNotesScrollArea, 0, 0, 1, 1)
        self.column3Splitter.addWidget(self.allNotesGroupBox)
        
        self.addNotesButton = QtWidgets.QPushButton("Add Notes")
        self.addNotesButton.setSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        self.addNotesButton.setMaximumHeight(50)  # Set maximum height for the "Add" button
        self.column3Splitter.addWidget(self.addNotesButton)
        
        self.topicGroupBox = QtWidgets.QGroupBox("Topic")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.topicGroupBox)
        self.topicTextEdit = QtWidgets.QTextEdit()
        self.topicTextEdit.setMaximumHeight(50)  # Set maximum height for the "Topic" text edit
        self.gridLayout_5.addWidget(self.topicTextEdit, 0, 0, 1, 1)
        self.column3Splitter.addWidget(self.topicGroupBox)
        
        # Set the stretch factors for the splitter to allocate more space to the notes list view
        self.column3Splitter.setStretchFactor(0, 4)  # Larger stretch factor for "All Notes" section
        self.column3Splitter.setStretchFactor(1, 1)  # Smaller stretch factor for "Add" button
        self.column3Splitter.setStretchFactor(2, 1)  # Smaller stretch factor for "Topic" section


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tableGroupBox.setTitle(_translate("MainWindow", "Questions"))
        self.addQPushButton.setText(_translate("MainWindow", "Add Question"))
        self.sortLineEdit.setPlaceholderText(_translate("MainWindow", "Sort Identifier"))
        self.numIDLineEdit.setPlaceholderText(_translate("MainWindow", "Numerical Identifier"))
        self.titleGroupBox.setTitle(_translate("MainWindow", "Title"))
        self.notesGroupBox.setTitle(_translate("MainWindow", "Notes"))
        self.allNotesGroupBox.setTitle(_translate("MainWindow", "All Notes"))
        self.addNotesButton.setText(_translate("MainWindow", "Add Notes"))
        self.topicGroupBox.setTitle(_translate("MainWindow", "Topic"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuNote.setTitle(_translate("MainWindow", "Note"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionExport.setText(_translate("MainWindow", "Export"))
        self.actionNew_Cloze.setText(_translate("MainWindow", "New Cloze"))
        self.actionSame_Cloze.setText(_translate("MainWindow", "Same Cloze"))
        self.actionBold.setText(_translate("MainWindow", "Bold"))
        self.actionUnderline.setText(_translate("MainWindow", "Underline"))
        self.actionItalicize.setText(_translate("MainWindow", "Italicize"))
        self.actionAdd_Note.setText(_translate("MainWindow", "Add Note"))
        self.actionAdd_Note.setShortcut(_translate("MainWindow", "Ctrl+M"))
        self.actionAdd_Card.setText(_translate("MainWindow", "Add Card"))